server:
    context-path: /ofm-da-core/v2
    compression: # 配置压缩
            enabled: true
            mime-types: text/html,text/xml,text/plain,application/json,application/xml,application/javascript
            min-response-size: 2048

logging:
    config: classpath:ofm-logback.xml
    file: logs/log.txt
    #path: #保存日志文件目录路径
    #config: logback.xml #日志配置文件,Spring Boot默认使用classpath路径下的日志配置文件,如:logback.xml
    level:
        tk.mybatis: DEBUG
        com.siemens.dasheng.web.mapper: info
        org.springframework.web: info #配置spring web日志级别

spring:
    http.multipart.maxFileSize: 10Mb
    http.multipart.maxRequestSize: 10Mb
    application:
        name: ofm-da-core
    datasource:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        minIdle: 5
        initialSize: 5
        maxActive: 60
        maxWait: 120000
        maxOpenPreparedStatements: 20
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        remove-abandoned: true
        idle-timeout: 600000
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    freemarker:
        cache: false
        request-context-attribute: request

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

env:
  name: UNIT_TEST